name: CI

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    actions: read
    contents: write
    deployments: write
    packages: write
    attestations: write
    id-token: write

jobs:
    main:
        runs-on: ubuntu-latest
        concurrency:
          group: main-ci
          cancel-in-progress: true
        env:
            is-master: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        steps:
            - name: "git: checkout"
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: "pnpm: setup"
              uses: pnpm/action-setup@v4
              with:
                  version: "10.6.2"
                  run_install: false # to cache in the next step

            - name: "node: setup"
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "pnpm"

            - name: "pnpm: install"
              run: pnpm install --frozen-lockfile

            - name: "nx: set shas"
              uses: nrwl/nx-set-shas@v4
              with:
                  main-branch-name: master

            - name: "nx: format check"
              shell: bash
              run: pnpm exec nx format:check

            - name: "nx: affected lint, test"
              shell: bash
              run: pnpm exec nx affected -t lint, test

            - name: "nx: affected deploy"
              env:
                  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NX_BRANCH: ${{ github.head_ref || github.ref_name }}
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              shell: bash
              run: pnpm exec nx affected -t deploy --configuration=${{ env.is-master == 'true' && 'production' || 'staging' }}
